/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package foodhub;

/**
 *
 * @author Chan Jia Zhil
 */
public class CartCard extends javax.swing.JPanel {

    /**
     * Creates new form CartCard
     */
    public CartCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartPic = new javax.swing.JLabel();
        cartFoodName = new javax.swing.JLabel();
        cartQuantity = new javax.swing.JLabel();
        cartTotalPrice = new javax.swing.JLabel();
        cartDelete = new javax.swing.JToggleButton();
        cartEdit = new javax.swing.JToggleButton();
        cartPrice = new javax.swing.JLabel();

        cartPic.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cartPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartPic.setText("Pic");

        cartFoodName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cartFoodName.setText("Food Name");

        cartQuantity.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cartQuantity.setText("Quan");

        cartTotalPrice.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cartTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartTotalPrice.setText("Price");

        cartDelete.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cartDelete.setText("🗑️");

        cartEdit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cartEdit.setText("Edit");
        cartEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartEditActionPerformed(evt);
            }
        });

        cartPrice.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cartPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartPrice.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cartPic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cartFoodName)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cartPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cartQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cartEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cartTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cartDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cartPic, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cartFoodName)
                            .addComponent(cartDelete))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cartQuantity)
                            .addComponent(cartEdit))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cartPrice)
                    .addComponent(cartTotalPrice))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cartEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JToggleButton cartDelete;
    protected javax.swing.JToggleButton cartEdit;
    protected javax.swing.JLabel cartFoodName;
    protected javax.swing.JLabel cartPic;
    protected javax.swing.JLabel cartPrice;
    protected javax.swing.JLabel cartQuantity;
    protected javax.swing.JLabel cartTotalPrice;
    // End of variables declaration//GEN-END:variables
}
