/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package foodhub;

/**
 *
 * @author Chan Jia Zhil
 */
public class FoodCard extends javax.swing.JPanel {

    /**
     * Creates new form VendorCard
     */
    public FoodCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        foodName = new javax.swing.JLabel();
        foodImage = new javax.swing.JButton();
        foodPrice = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        foodName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        foodName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodName.setText("Food Name");
        foodName.setToolTipText("");

        foodImage.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        foodImage.setText("Food Image");
        foodImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodImageActionPerformed(evt);
            }
        });

        foodPrice.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        foodPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodPrice.setText("Food Price");
        foodPrice.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foodName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(foodPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(foodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foodName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foodPrice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void foodImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodImageActionPerformed
        
    }//GEN-LAST:event_foodImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton foodImage;
    protected javax.swing.JLabel foodName;
    protected javax.swing.JLabel foodPrice;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
