/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodhub;

import java.awt.Font;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
            
/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();  
        setLocationRelativeTo(null);  //spawn window at center of screen
        
        java.net.URL imageURL = getClass().getResource("/foodhub/images/Foodhub.png");
        ImageIcon image = new ImageIcon(imageURL);
        setIconImage(image.getImage());    //set window logo 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        tfUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        tfPassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(660, 550));
        setPreferredSize(new java.awt.Dimension(660, 550));
        getContentPane().setLayout(null);

        tfUser.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });
        getContentPane().add(tfUser);
        tfUser.setBounds(170, 270, 320, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setText("Login");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 160, 110, 50);

        jLabel4.setBackground(new java.awt.Color(247, 127, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 220, 320, 5);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 310, 185, 24);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Username");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 240, 185, 24);

        jToggleButton1.setForeground(new java.awt.Color(84, 96, 107));
        jToggleButton1.setText("👁");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(450, 340, 40, 30);

        tfPassword.setEchoChar('•');
        tfPassword.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        getContentPane().add(tfPassword);
        tfPassword.setBounds(170, 340, 320, 30);

        jButton2.setBackground(new java.awt.Color(247, 127, 102));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Login");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 400, 100, 30);

        jLabel7.setForeground(new java.awt.Color(99, 116, 130));
        jLabel7.setText("Don't have an account?");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 450, 130, 16);

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(16, 55, 86));
        jButton1.setText("Sign Up");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 450, 50, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodhub/images/Foodhub.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(374, 500));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 30, 110, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodhub/images/Foodhub.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(374, 500));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 30, 110, 130);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodhub/images/1920x1080-white.jpg"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(640, 550));
        jLabel8.setMinimumSize(new java.awt.Dimension(640, 550));
        jLabel8.setName(""); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, -10, 680, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()) {
            tfPassword.setEchoChar((char) 0);
        } else {
            tfPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

    UIManager.put("OptionPane.messageFont", new Font("Sans Serif", Font.PLAIN, 14));

    try {
        UserManager userManager = new UserManager(FilePaths.USER_FILE);

        String username = tfUser.getText().trim();
        String password = new String(tfPassword.getPassword()).trim();

        // Validate input fields
        if (username.isEmpty() || password.isEmpty()) {
            new DialogManager("Login failed").showInfoMessage("Please fill in the blanks.");
            return;
        }

        // Check if username exists
        if (!userManager.isUsernameExists(username)) {
            new DialogManager("Authentication failed").showInfoMessage("Username does not exist, please try again.");
            return;
        }

        // Authenticate user
        if (userManager.authenticate(username, password)) {
            System.out.println("Successful Login by: " + username);

            // Get user role and ID
            User loggedInUser = userManager.getUserByUsername(username); // You need to create this method
            if (loggedInUser == null) {
                new DialogManager("Authentication failed").showErrorMessage("Failed to retrieve user details.");
                return;
            }

            String userID = loggedInUser.getUserID();
            String role = loggedInUser.getRole(); // Role stored as a string, e.g., "0", "1", etc.

            // Set session ID
            SessionManager.getInstance().setSessionID(userID);
            System.out.println("Session ID Set: " + userID);

            // Close login window
            dispose();
        } else {
            new DialogManager("Authentication failed").showInfoMessage("Incorrect password, please try again.");
        }

    } catch (HeadlessException e) {
        new DialogManager("An unexpected error occurred").showErrorMessage("Error, please report to the administrator.");
    }

     
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SignUp signUp = new SignUp();
        signUp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
