/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodhub;

import foodhub.DialogManager;
import foodhub.FilePaths;
import foodhub.Login;
import foodhub.UserManager;
import foodhub.ValidationManager;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class SignUp extends javax.swing.JFrame {

    String[] placeholders = {"e.g. abc123", "Alison Burger", "Slava@gmail.com", "e.g. 60123456789", "e.g. abc123_$%", ""};
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        
        setLocationRelativeTo(null);  //spawn window at center of screen
        
        java.net.URL imageURL = getClass().getResource("/foodhub/images/Foodhub.png");
        ImageIcon image = new ImageIcon(imageURL);
        setIconImage(image.getImage());    //set window logo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        tfPhoneNumber = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        tfConfirmPassword = new javax.swing.JPasswordField();
        tfPassword = new javax.swing.JPasswordField();
        tfUsername = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        choice1 = new java.awt.Choice();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 550));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Let's get you started!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 241, 32);

        jLabel2.setText("The perfect food requires your perfect credentials");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 60, 272, 16);

        jLabel4.setBackground(new java.awt.Color(247, 127, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 100, 400, 4);

        jToggleButton1.setForeground(new java.awt.Color(84, 96, 107));
        jToggleButton1.setText("👁");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(480, 210, 40, 30);

        tfPhoneNumber.setBackground(new java.awt.Color(250, 250, 250));
        tfPhoneNumber.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        tfPhoneNumber.setForeground(new java.awt.Color(153, 153, 153));
        tfPhoneNumber.setText("e.g. 60123456789");
        tfPhoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPhoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPhoneNumberFocusLost(evt);
            }
        });
        tfPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneNumberActionPerformed(evt);
            }
        });
        getContentPane().add(tfPhoneNumber);
        tfPhoneNumber.setBounds(120, 340, 210, 30);

        jToggleButton2.setForeground(new java.awt.Color(84, 96, 107));
        jToggleButton2.setText("👁");
        jToggleButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToggleButton2.setContentAreaFilled(false);
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(480, 280, 40, 30);

        tfConfirmPassword.setEchoChar('•');
        tfConfirmPassword.setBackground(new java.awt.Color(250, 250, 250));
        tfConfirmPassword.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        tfConfirmPassword.setForeground(new java.awt.Color(153, 153, 153));
        tfConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfConfirmPasswordFocusLost(evt);
            }
        });
        tfConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfConfirmPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfConfirmPassword);
        tfConfirmPassword.setBounds(120, 280, 400, 30);

        tfPassword.setEchoChar('•');
        tfPassword.setBackground(new java.awt.Color(250, 250, 250));
        tfPassword.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(153, 153, 153));
        tfPassword.setText("e.g. abc123_$%");
        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPasswordFocusLost(evt);
            }
        });
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfPassword);
        tfPassword.setBounds(120, 210, 400, 30);

        tfUsername.setBackground(new java.awt.Color(250, 250, 250));
        tfUsername.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(153, 153, 153));
        tfUsername.setText("e.g. abc123");
        tfUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(tfUsername);
        tfUsername.setBounds(120, 150, 400, 30);

        jButton2.setBackground(new java.awt.Color(247, 127, 102));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign Up");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 400, 100, 31);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jButton1.setText("Log In");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 450, 50, 16);

        choice1.addItem("Customer");
        choice1.addItem("Vendor");
        choice1.addItem("Runner");
        //    choice1.addItem("Admin");
        //    choice1.addItem("Manager");
        choice1.setMinimumSize(new java.awt.Dimension(64, 60));
        choice1.setName(""); // NOI18N
        getContentPane().add(choice1);
        choice1.setBounds(340, 340, 180, 30);
        choice1.getAccessibleContext().setAccessibleName("");

        jLabel7.setText("Already have an account?");
        jLabel7.setToolTipText("");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 450, 150, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 130, 80, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Role");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 320, 40, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Confirm Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 260, 130, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Password");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(120, 190, 130, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Phone Number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 320, 130, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodhub/images/1920x1080-white.jpg"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(640, 550));
        jLabel8.setMinimumSize(new java.awt.Dimension(640, 550));
        jLabel8.setName(""); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -10, 680, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()) {
            tfPassword.setEchoChar((char) 0);
        } else {
            tfPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void tfPhoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPhoneNumberFocusGained
        // TODO add your handling code here:
        if (tfPhoneNumber.getText().equals(placeholders[3])) {
          tfPhoneNumber.setText("");
          tfPhoneNumber.setForeground(new Color(0, 0, 0));
       }
    }//GEN-LAST:event_tfPhoneNumberFocusGained

    private void tfPhoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPhoneNumberFocusLost
        // TODO add your handling code here:
       if (tfPhoneNumber.getText().equals("")) {
          tfPhoneNumber.setText(placeholders[3]);
          tfPhoneNumber.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_tfPhoneNumberFocusLost

    private void tfPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneNumberActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton2.isSelected()) {
            tfConfirmPassword.setEchoChar((char) 0);
        } else {
            tfConfirmPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void tfConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfConfirmPasswordFocusGained
        // TODO add your handling code here:
       if (String.valueOf(tfConfirmPassword.getPassword()).equals(placeholders[5])) {
           tfConfirmPassword.setText("");
           tfConfirmPassword.setForeground(new Color(0, 0, 0));
       }
    }//GEN-LAST:event_tfConfirmPasswordFocusGained

    private void tfConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfConfirmPasswordFocusLost
        // TODO add your handling code here:
        if (String.valueOf(tfConfirmPassword.getPassword()).equals("")) {
          tfConfirmPassword.setText(placeholders[5]);
          tfConfirmPassword.setForeground(new Color(153, 153, 153));
       }
    }//GEN-LAST:event_tfConfirmPasswordFocusLost

    private void tfConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfConfirmPasswordActionPerformed

    private void tfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusGained
        // TODO add your handling code here:
        if (String.valueOf(tfPassword.getPassword()).equals(placeholders[4])) {
            tfPassword.setText("");
          tfPassword.setForeground(new Color(0, 0, 0));
      }
    }//GEN-LAST:event_tfPasswordFocusGained

    private void tfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusLost
        // TODO add your handling code here:
       if (String.valueOf(tfPassword.getPassword()).equals("")) {
            tfPassword.setText(placeholders[4]);
            tfPassword.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_tfPasswordFocusLost

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void tfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusGained
        // TODO add your handling code here:
     if (tfUsername.getText().equals(placeholders[0])) {
            tfUsername.setText("");
           tfUsername.setForeground(new Color(0, 0, 0));
       }
    }//GEN-LAST:event_tfUsernameFocusGained

    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        // TODO add your handling code here:
        if (tfUsername.getText().equals("")) {
         tfUsername.setText(placeholders[0]);
          tfUsername.setForeground(new Color(153, 153, 153));
      }
    }//GEN-LAST:event_tfUsernameFocusLost

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        // Create an instance of ValidationManager
        ValidationManager verify = new ValidationManager();

        String username = tfUsername.getText().trim();
        String phoneNumber = tfPhoneNumber.getText().trim();
        String password = new String(tfPassword.getPassword());
        String confirmPassword = new String(tfConfirmPassword.getPassword());
        String role = choice1.getSelectedItem();
        String errorMessage = "Error(s):\n";
        boolean inputError = false;

        DialogManager dialogManager = new DialogManager("Registration failed!");

        // **Validation Using ValidationManager**
        if (!verify.nullCheck(username) || username.equals(placeholders[0])) {
            inputError = true;
            errorMessage += "- Username cannot be empty!\n";
        } else if (!verify.characterCheck(username)) {
            inputError = true;
            errorMessage += "- Username should not contain special characters!\n";
        }

        if (!verify.nullCheck(phoneNumber) || phoneNumber.equals(placeholders[3])) {
            inputError = true;
            errorMessage += "- Phone number cannot be empty!\n";
        } else if (!verify.phoneValidation(phoneNumber)) {
            inputError = true;
            errorMessage += "- Invalid phone number format!\n";
        }

        if (!verify.nullCheck(password) || password.equals(placeholders[4])) {
            inputError = true;
            errorMessage += "- Password cannot be empty!\n";
        } else if (!verify.passwordValidation(password)) {
            inputError = true;
            errorMessage += "- Password must be at least 8 characters, contain one number, and one special character!\n";
        }

        if (!verify.nullCheck(confirmPassword) || confirmPassword.equals(placeholders[5])) {
            inputError = true;
            errorMessage += "- Confirm password cannot be empty!\n";
        } else if (!confirmPassword.equals(password)) {
            inputError = true;
            errorMessage += "- Passwords do not match!\n";
        }

        if (inputError) {
            dialogManager.showErrorMessage(errorMessage);
            return;
        }

        // **Role Conversion**
        String convertedValue;
        switch (role) {
            case "Customer" -> convertedValue = "4";
            case "Vendor" -> convertedValue = "2";
            case "Runner" -> convertedValue = "3";
            case "Admin" -> convertedValue = "1";
            case "Manager" -> convertedValue = "0";
            default -> {
                dialogManager.showInfoMessage("Please select a valid role.");
                return;
            }
        }

        int roleNumber = Integer.parseInt(convertedValue);

        // **Register User**
        UserManager userManager = new UserManager(FilePaths.USER_FILE);
        boolean isRegistered = userManager.registerUser(username, phoneNumber, roleNumber, password, null);

        if (isRegistered) {
            dialogManager.setTitle("Registration successful");
            dialogManager.showInfoMessage("You have successfully registered.");
            new Login().setVisible(true);
            this.dispose();
        } else {
            dialogManager.showErrorMessage("User registration failed.");
        }
    

            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      Login login = new Login();
      login.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SignUp().setVisible(true);
        });
    }

    
    private void resetToPlaceholder(JTextField field, String placeholder) {
    field.setText(placeholder);
    field.setForeground(new Color(153, 153, 153));
}
    
    private boolean containsSpecialCharacters(String input) {
    return input.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/? ].*");
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JPasswordField tfConfirmPassword;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfPhoneNumber;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
