/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package foodhub;

/**
 *
 * @author Chan Jia Zhil
 */
public class VendorCard extends javax.swing.JPanel {

    /**
     * Creates new form VendorCard
     */
    public VendorCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vendorName = new javax.swing.JLabel();
        vendorRating = new javax.swing.JLabel();
        vendorImage = new javax.swing.JButton();
        vendorStarImg = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        vendorName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        vendorName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vendorName.setText("Vendor Name");
        vendorName.setToolTipText("");
        vendorName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        vendorRating.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        vendorRating.setText("Rating");

        vendorImage.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        vendorImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vendorImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorImageActionPerformed(evt);
            }
        });

        vendorStarImg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        vendorStarImg.setText("⭐");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vendorName, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(vendorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(vendorRating, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendorStarImg)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(vendorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendorName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorStarImg)
                    .addComponent(vendorRating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vendorImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorImageActionPerformed
        
    }//GEN-LAST:event_vendorImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    protected javax.swing.JButton vendorImage;
    protected javax.swing.JLabel vendorName;
    protected javax.swing.JLabel vendorRating;
    protected javax.swing.JLabel vendorStarImg;
    // End of variables declaration//GEN-END:variables
}
